### PR TITLE
Avoid duplicate member if possible

### PR DESCRIPTION
**Pull request by tsarma**

### CODE REVIEW

**Comment by tsarma** [comment]
as discussed here https://github.com/inspiredminds/contao-facebook-login/pull/10

**Comment by fritzmg** [comment]
Actually this should not be done for security reasons. Existing accounts should only be connected to Facebook by the user themself using the appropriate module while being logged in.

**Comment by tsarma** [comment]
I don't see any security issues (or are you talking from DSGVO aspect), maybe I am wrong. 

I agree when you say, users should be given an option to connect their account with facebook on their own. And this I see as a separate feature in another separate extension. 

But with facebook login, the situation is a little different, because user has opted to use facebook account to log into website and when that user happened to be in the system we just update his/her facebook id. 
Otherwise saving any data from facebook in our system first place should be questionable.

**Comment by fritzmg** [comment]
> I don't see any security issues (or are you talking from DSGVO aspect), maybe I am wrong.

Conceivably, you could change your Facebook E-Mail address to that of another existing user (that is not connected to Facebook) and thus hijack the account this way. It wouldn't work, because Facebook would need to verify that you own the e-mail address, but it is a theoretical attack vector.

> I agree when you say, users should be given an option to connect their account with facebook on their own. And this I see as a separate feature in another separate extension.

This has already been implemented. See https://github.com/inspiredminds/contao-facebook-login/pull/8

**Comment by tsarma** [comment]
Since you have to verify email on facebook. Changing email in facebook to another existing Contao member should not work as you pointed out. If you've still nagging feeling then let it be as now, we'll think over it for some time.

**Comment by fritzmg** [comment]
Yeah, but what if someone hijacked the Facebook account for example. Then the hijacker would be able to gain access to the Contao installation's account as well, even if the user did not connect to Facebook before, but merely used the same email address.

As I said, existing users must use the connect feature.

**Comment by tsarma** [comment]
> If someone hijacked the Facebook account for example. Then the hijacker would be able to gain access to the Contao installation's account as well

Then my suggestion from the other day should be worth considering, namely disable `tl_member.facebookId`. Admin should not consolidate accounts at all, and also why let the user to connect facebook (maybe this one, you might argue that user opted by himself).

**Comment by fritzmg** [comment]
> Then my suggestion from the other day should be worth considering, namely disable tl_member.facebookId. Admin should not consolidate accounts at all

Why not?

> and also why let the user to connect facebook

Why not? This is a feature you see in many web services.

**Comment by tsarma** [comment]
My understanding of `consolidate accounts` is, to merge double accounts of the same user who is already a registered member (Contao registered, without tl_member.facebookId), but at some time in future, if he logins in with his facebook account, Contao creates a new member with the same email. In such a case, as an admin, I would update `tl_member.facebookId` of one account and remove the duplicate account.
 
Now as you pointed out if the facebook account is hacked, then the hijacker gains access to the Contao account. That's why I am telling admin should not consolidate account.

**Comment by fritzmg** [comment]
> My understanding of `consolidate accounts` is, to merge double accounts of the same user who is already a registered member (Contao registered, without tl_member.facebookId), but at some time in future, if he logins in with his facebook account, Contao creates a new member with the same email. In such a case, as an admin, I would update `tl_member.facebookId` of one account and remove the duplicate account.

Yes, exactly.

> Now as you pointed out if the facebook account is hacked, then the hijacker gains access to the Contao account. That's why I am telling admin should not consolidate account.

That's up to the admin then. Besides, it does not matter if the field is removed from the palette. One can as easily add it to the palette again, as you can remove it. If, for your use-case, you think it is best to remove it from the palette, then adjust the DCA accordingly for your application.

**Comment by tsarma** [comment]
OK, I'll adjust accordingly on my needs. 🙏  Thanks for the round of discussion.

**Pull request closed without merging**
