### PR TITLE
Id should be string

### PR DESCRIPTION
**Pull request by tsarma**

### CODE REVIEW

**Comment by fritzmg** [comment]
I have actually fixed this in https://github.com/fritzmg/contao-facebook-js-sdk/commit/9520a763a597d90ff619a012452e4713e9920746 now. The problem is, that `\Contao\Config::escape` does not put numbers (that are lower than `PHP_INT_MAX`) into quotes. Thus the purely numeric Facebook App ID gets saved as an integer in `system/config/localconfig.php`, which will then be returned as an integer of course. The fix is released in version `3.2.4` of `fritzmg/contao-facebook-js-sdk`.

**Comment by tsarma** [comment]
You have forgotten to integrate this change in 2.3.0. Now, I can not log in with facebook.  Error log in Contao says `Access token metadata contains unexpected app ID.`

**Comment by fritzmg** [comment]
@tsarma which version of `fritzmg/contao-facebook-js-sdk` do you have installed? It should be fixed in version `3.2.1`.

**Comment by tsarma** [comment]
My composer lock says:
`
"name": "fritzmg/contao-facebook-js-sdk",
"version": "3.2.3",
`

**Comment by fritzmg** [comment]
Sorry, I meant `3.2.4`. You need to update your packages.

**Comment by tsarma** [comment]
Yes, it works with `fritzmg/contao-facebook-js-sdk` version `3.2.4`. Thanks

**Pull request closed without merging**
